### ISSUE TITLE
API server not working on GAE

### ISSUE THREAD

**Issue by suessmann** [studioml/studio#291]
Hello!

I faced a trouble deploying the API server to GAE. So, I went through [your guide](https://github.com/studioml/studio/blob/master/docs/setup_database.rst) on setting up a database and it worked well for a local server, however when I deployed the same api on GAE and then followed the url of a deployed server, in browser it returned `500 Server Error`. Acessing a Google Cloud Console gave me an insight that the breakpoint here is a script `credentials.py`, because running it in GAE rises the following exception:
```
File "/base/data/home/apps/s~bigsimnum/.../lib/botocore/credentials.py", 
line 716, in ProcessProvider
def __init__(self, profile_name, load_config, popen=subprocess.Popen):
AttributeError: 'module' object has no attribute 'Popen'
```
As I see the problem, Google does not allow system calls inside their GAE sandbox. At the same time, I guess it is still possible to deploy a server there, so probably I make a mistake at some point.

Version: 54d4bfb0ccda6095ce8b7b5b7a6b89d260bd9be3
Platform: OSX 10.13 (17A405)
Python: Python 2.7.9 in virtualenv

My server config is attached. 
[apiserver_config.txt](https://github.com/studioml/studio/files/1506529/apiserver_config.txt)

**Comment by pzhokhov** [comment]
Hi @suessmann ! Thanks for pointing that out, this is definitely a bug. I'll fix it shortly, but in the meantime as a workaround you can use google storage instead of firebase to store experiment information (we are using that for hosted API server at zoo.studio.ml, and that's probably why the bug was not uncovered before).  Here is an example of config.yaml file that accomplishes that:
```
database:
    type: gs
    apiKey: <your firebase API key>
    authDomain: "bigsumnum.firebaseapp.com"
    bucket: "bigsumnum-meta"

    guest: true
    use_email_auth: false
    projectId: bigsumnum

storage:
    type: gcloud
    bucket:bigsumnum.appspot.com
```
